// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'objectbox/models/history_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5817989710624562224),
    name: 'HistoryModel',
    lastPropertyId: const obx_int.IdUid(11, 8898907657132271464),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5969049130498169375),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8633218427877066148),
        name: 'databaseId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 4102341843562228065),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8608543054645976576),
        name: 'resourceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1274479251373722504),
        name: 'apiKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7177841822424511874),
        name: 'sourceGroupKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2251661143845904441),
        name: 'chapterUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2717335028105174494),
        name: 'chapterIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3661223770468794231),
        name: 'chapterName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 571058829363488277),
        name: 'durationInMilli',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5004601039758401042),
        name: 'positionInMilli',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8898907657132271464),
        name: 'time',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 5817989710624562224),
    lastIndexId: const obx_int.IdUid(1, 4102341843562228065),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    HistoryModel: obx_int.EntityDefinition<HistoryModel>(
      model: _entities[0],
      toOneRelations: (HistoryModel object) => [],
      toManyRelations: (HistoryModel object) => {},
      getId: (HistoryModel object) => object.id,
      setId: (HistoryModel object, int id) {
        object.id = id;
      },
      objectToFB: (HistoryModel object, fb.Builder fbb) {
        final databaseIdOffset = fbb.writeString(object.databaseId);
        final resourceIdOffset = fbb.writeString(object.resourceId);
        final apiKeyOffset = object.apiKey == null
            ? null
            : fbb.writeString(object.apiKey!);
        final sourceGroupKeyOffset = object.sourceGroupKey == null
            ? null
            : fbb.writeString(object.sourceGroupKey!);
        final chapterUrlOffset = fbb.writeString(object.chapterUrl);
        final chapterNameOffset = fbb.writeString(object.chapterName);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, databaseIdOffset);
        fbb.addOffset(2, resourceIdOffset);
        fbb.addOffset(3, apiKeyOffset);
        fbb.addOffset(4, sourceGroupKeyOffset);
        fbb.addOffset(5, chapterUrlOffset);
        fbb.addInt64(6, object.chapterIndex);
        fbb.addOffset(7, chapterNameOffset);
        fbb.addInt64(8, object.durationInMilli);
        fbb.addInt64(9, object.positionInMilli);
        fbb.addInt64(10, object.time.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final databaseIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final resourceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final apiKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final sourceGroupKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final chapterUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final chapterIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final chapterNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final durationInMilliParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final positionInMilliParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final timeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final object = HistoryModel(
          databaseId: databaseIdParam,
          resourceId: resourceIdParam,
          apiKey: apiKeyParam,
          sourceGroupKey: sourceGroupKeyParam,
          chapterUrl: chapterUrlParam,
          chapterIndex: chapterIndexParam,
          chapterName: chapterNameParam,
          durationInMilli: durationInMilliParam,
          positionInMilli: positionInMilliParam,
          time: timeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [HistoryModel] entity fields to define ObjectBox queries.
class HistoryModel_ {
  /// See [HistoryModel.id].
  static final id = obx.QueryIntegerProperty<HistoryModel>(
    _entities[0].properties[0],
  );

  /// See [HistoryModel.databaseId].
  static final databaseId = obx.QueryStringProperty<HistoryModel>(
    _entities[0].properties[1],
  );

  /// See [HistoryModel.resourceId].
  static final resourceId = obx.QueryStringProperty<HistoryModel>(
    _entities[0].properties[2],
  );

  /// See [HistoryModel.apiKey].
  static final apiKey = obx.QueryStringProperty<HistoryModel>(
    _entities[0].properties[3],
  );

  /// See [HistoryModel.sourceGroupKey].
  static final sourceGroupKey = obx.QueryStringProperty<HistoryModel>(
    _entities[0].properties[4],
  );

  /// See [HistoryModel.chapterUrl].
  static final chapterUrl = obx.QueryStringProperty<HistoryModel>(
    _entities[0].properties[5],
  );

  /// See [HistoryModel.chapterIndex].
  static final chapterIndex = obx.QueryIntegerProperty<HistoryModel>(
    _entities[0].properties[6],
  );

  /// See [HistoryModel.chapterName].
  static final chapterName = obx.QueryStringProperty<HistoryModel>(
    _entities[0].properties[7],
  );

  /// See [HistoryModel.durationInMilli].
  static final durationInMilli = obx.QueryIntegerProperty<HistoryModel>(
    _entities[0].properties[8],
  );

  /// See [HistoryModel.positionInMilli].
  static final positionInMilli = obx.QueryIntegerProperty<HistoryModel>(
    _entities[0].properties[9],
  );

  /// See [HistoryModel.time].
  static final time = obx.QueryDateProperty<HistoryModel>(
    _entities[0].properties[10],
  );
}
